require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

$FirebaseSDKVersion = '8.10.0'

platform :ios, '13.0'

target 'BjJewells' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )




  # pod 'react-native-image-base64', :path => '../node_modules/react-native-image-base64'

  # pod 'RNAudioRecord', :path => '../node_modules/react-native-audio-record'
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  
  target 'BjJewellsTests' do
    inherit! :complete
    # Pods for testing
  
  
 
 
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  #use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
